# Generated by Django 3.0.3 on 2020-08-01 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.TextField(default='this is cool!'),
        ),
        migrations.AddField(
            model_name='blog',
            name='summary',
            field=models.TextField(default='amazing'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.TextField(default='wow'),
        ),
    ]
